name: Build and Release
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g electron-builder
          
      - name: Build application
        run: |
          echo "Starting build process..."
          npm run build
          ls -R dist/  # List built files
          
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Creating release for tag ${GITHUB_REF##*/}"
          gh release create ${GITHUB_REF##*/} ./dist/*.exe
